### ISSUE TITLE
issue with the bot answering

### ISSUE THREAD

**Issue by ahmar464** [dev-kian/DalleTelegramBot#2]
![Screenshot 2024-07-05 110514](https://github.com/dev-kian/DalleTelegramBot/assets/174827364/82157c8b-d1ca-4458-a468-4e923fc347b4)

ive done all the 10 steps provided i.e entering api_key, user_id and bot_token in appsettings.json.
i would appreciate help as soon as possible.

Thanks

**Comment by dev-kian** [comment]
Hello, make sure the appsettings data is correct, and give a screenshot of the console logger.
