### ISSUE TITLE
Problem has occurred while processing image

### ISSUE THREAD

**Issue by Jero-OT** [dev-kian/DalleTelegramBot#3]
Hi all,

The current code is given problems while trying to generate an image:

<img width="361" alt="1" src="https://github.com/user-attachments/assets/64f403be-ac4a-4d06-99ba-0c6793c6e2b3">

**Comment by dev-kian** [comment]
Get the error log from the bot settings section and send the error that occurred in that log, including the "test" command, it is not correct to check the bot, use a better command to make a photo!
